<?php


use Autoversioner\Config\GitHubCredentials;

class GitHubCredentialsTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var GitHubCredentials
     */
    private $githubCredentials;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $config = ['username'=>'foo','token'=>'bar'];
        $this->githubCredentials = new GitHubCredentials($config);
    }


    public function testGetUserName()
    {
        $this->assertEquals($this->githubCredentials->getUserName(), 'foo');
    }

    public function testGetToken()
    {
        $this->assertEquals($this->githubCredentials->getToken(), 'bar');
    }
}
